
# modbus设置
modbus_setting:
  ip_str: 127.0.0.1
  port: 502


# 相机设置
camera_setting:
  camera_num: 1
  camera_run_type: 1 # 0：硬触发运行，1：自由运行
  exposure_time: 30
  field_of_view_X_mm: 50  #长度 落地
  head_tail_distance_mm: 14
  resolution_X: 2048
  resolution_Y: 800




# 检测算法相关参数
blob_setting:
  mark_num: 5
  mark_type: 1 # 0：菱形标，1：圆形标
  mark_width: [1, 1.5] # 菱形对角线 圆形直径
  mark_height: [1, 1.5]
  rectangularity: [1, 0.785]  # PI/4 = 0.785
  limit: [0.6, 1.6]  # [0.7, 1.2]，筛选面积和长宽的最大最小倍数范围

  scaling: 3  # 3，先缩小3倍粗检测，时间花费和精度都比较合适
  blur_kernel: 35  # 9，处理之前高斯滤波窗口大小，9比较合适
  adaptive_block: 67  # 67，自适应二值化的窗口大小，对于目前测试的大小矩形标和三角标都较为合适
  C: 3  # 12，自适应二值化的阈值偏差, 光亮直接相关！！！！！
  C1: 0
  C2: 0
